# Experiment 1: Inspect the Sparse Representation

- Đọc raw corpus đã cho ở thư mục `data` và lưu các document trong corpus vào `list`

In [1]:
import gzip
import json

data_path = '../data/c4-train.00000-of-01024-30K.json.gz'

corpus = []

with gzip.open(data_path, 'rt', encoding = 'utf-8') as f:
    for line in f:
        data = json.loads(line)
        corpus.append(data['text'])

- In ra một document bất kỳ và số lượng document sau khi đọc dữ liệu

In [2]:
print(corpus[0])
print('--------')
print(f'Number of documents: {len(corpus)}')

Beginners BBQ Class Taking Place in Missoula!
Do you want to get better at making delicious BBQ? You will have the opportunity, put this on your calendar now. Thursday, September 22nd join World Class BBQ Champion, Tony Balay from Lonestar Smoke Rangers. He will be teaching a beginner level class for everyone who wants to get better with their culinary skills.
He will teach you everything you need to know to compete in a KCBS BBQ competition, including techniques, recipes, timelines, meat selection and trimming, plus smoker and fire information.
The cost to be in the class is $35 per person, and for spectators it is free. Included in the cost will be either a t-shirt or apron and you will be tasting samples of each meat that is prepared.
--------
Number of documents: 30000

- Xây dựng pipeline biểu diễn ma trận TF-IDF trên dataset

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

# Tokenizer (tách từ) và CountVectorizer (vector hóa các document)
vectorizer = CountVectorizer(
    lowercase = True,       # Viết thường các từ
    tokenizer = str.split,  # Tách theo khoảng trắng
    token_pattern = None    # Tắt tính năng tách từ theo biểu thức chính quy
)

# Ma trận đếm từ xuất hiện trong corpus
count_matrix = vectorizer.fit_transform(corpus)
print(f'Count matrix shape: {count_matrix.shape}')

# Trích ra danh sách từ xuất hiện trong corpus
vocabulary_list = vectorizer.get_feature_names_out()
print(f'Vocabulary size: {len(vocabulary_list)}')

# Ma trận TF
document_lengths = np.asarray(count_matrix.sum(axis=1)).ravel()
tf_matrix = count_matrix.multiply(1 / document_lengths[:, None])

# Vector IDF
N = len(corpus)
df_vector = np.asarray((count_matrix > 0).sum(axis=0)).ravel() # Vector DF

idf_vector = np.log(N / df_vector)

# Ma trận TF-IDF
tf_idf_matrix = tf_matrix.multiply(idf_vector)
print(f'TF-IDF matrix shape: {tf_idf_matrix.shape}')

Count matrix shape: (30000, 473388)
Vocabulary size: 473388
TF-IDF matrix shape: (30000, 473388)

- N (số document): 30000
- V (số vocab): 473388

- Tính độ thưa (sparsity) của ma trận TF-IDF

In [4]:
S = 1 - (tf_idf_matrix.nnz / (N * len(vocabulary_list)))
print(f'Sparsity: {S * 100}%')

Sparsity: 99.96113415774516%

- Một document có thể sử dụng một số lượng vocabulary cực kỳ nhỏ nhưng count vector tương ứng có `V` chiều (số vocabulary) thể hiện:
    + Tính nhất quán trong biểu diễn: Sau khi vectorize dựa trên từ điển vocab được xây dựng từ corpus, các vocab không xuất hiện trong document sẽ đánh bằng giá trị 0, điều này đảm bảo tính nhất quán khi biểu diễn ma trận thưa TF-IDF gồm `V` cột, trong đó các document được biểu diễn các count vector `V` chiều, sau đó sẽ đưa vào xử lý và trở thành vector thưa TF-IDF, mỗi vector này đại diện cho mỗi hàng của ma trận kể trên.
    + Tính toán độ tương đồng giữa các document: Khi truy vấn từ document trong corpus sử dụng công thức cosine similarity, 2 vector đại diện cho 2 document bất kỳ tương ứng phải có cùng số chiều `V`, cho phép tính tích vô hướng và độ tương đồng giữa 2 document.

- Inspect vocabulary

In [5]:
k = 20

max_df_index = np.argsort(df_vector)[::-1][:k]
print('20 terms phổ biến nhất theo document frequency')
for i in max_df_index:
    print(f'{vocabulary_list[i]}: {df_vector[i]}')

20 terms phổ biến nhất theo document frequency
the: 27870
and: 27385
to: 26646
of: 25999
a: 25753
in: 25042
for: 23556
is: 22673
with: 21323
on: 19936
that: 18042
this: 17548
are: 17487
as: 16355
at: 16233
from: 16183
be: 16025
it: 15474
you: 15361
by: 14963

In [6]:
max_idf_index = np.argsort(idf_vector)[::-1][:k]
print('20 terms có IDF cao nhất')
for i in max_idf_index:
    print(f'{vocabulary_list[i]}: {idf_vector[i]}')

20 terms có IDF cao nhất
 : 10.308952660644293
🤳:: 10.308952660644293
🤰:: 10.308952660644293
🤢🤢: 10.308952660644293
🤢.: 10.308952660644293
🤗🤗🤗: 10.308952660644293
🤖:: 10.308952660644293
🙏🏻: 10.308952660644293
🙌🏻👯❤: 10.308952660644293
🙌: 10.308952660644293
🙋!!: 10.308952660644293
ever: 10.308952660644293
000: 10.308952660644293
: 10.308952660644293
=: 10.308952660644293
: 10.308952660644293
remarkable: 10.308952660644293
!!!!!!: 10.308952660644293
!!!!some: 10.308952660644293
!!!).: 10.308952660644293

In [7]:
import random

index_doc = random.randint(0, N)
tf_idf_val_arr = tf_idf_matrix.tocsr()[index_doc]

values = tf_idf_val_arr.data
term_indices = tf_idf_val_arr.indices

max_tf_idf_index = np.argsort(values)[::-1][:k]
print(f'20 terms có TF-IDF cao nhất trong document {index_doc}')

for i in max_tf_idf_index:
    print(f'{vocabulary_list[term_indices[i]]}: {values[i]}')

20 terms có TF-IDF cao nhất trong document 15237
can't: 0.23030485866399655
spas: 0.1829292118862068
spa: 0.17066467818653666
dreammaker: 0.16234571119124871
eden: 0.16165078955538345
certified: 0.1345975189958909
blue: 0.1182234887821615
virginia,: 0.10042719729007821
distributor: 0.0995270647886617
america: 0.09763193835917791
dealer: 0.08569162535730251
klear: 0.0757150037801917
krystal: 0.0757150037801917
regale: 0.07252236513367073
furnaces,: 0.07025715196475907
help.: 0.06634847398759162
spas,: 0.06479930014932643
away.: 0.06386021809557196
'n: 0.06160666150280545
discuss: 0.0592016050143383

- Một term xuất hiện nhiều trong corpus chưa chắc có TF-IDF cao, chẳng hạn có thể tồn tại term xuất hiện gần như mọi document trong corpus, nhờ đó mà tăng giá trị DF của term lên, nhưng đồng thời giá trị IDF giảm đi, từ đó giá trị TF-IDF của term trong document có thể thấp và ngược lại, có thể có term chỉ xuất hiện trong rất ít document, dẫn đến việc kéo giá trị IDF đi lên, nhờ đó mà giá trị TF-IDF của term trong document sẽ cao hơn.
- Một term có IDF cao chưa chắc có giá trị TF-IDF cao trong mọi document. Chẳng hạn sẽ có term xuất hiện nhiều ở document này, dẫn đến TF của term trong document sẽ cao hơn, dẫn đến giá trị TF-IDF của term sẽ cao, nhưng xét trên document khác, cũng là term đang xét nhưng tần suất xuất hiện ít hơn, từ đó mà TF của nó sẽ thấp hơn, và giá trị TF-IDF sẽ giảm đi.

# Experiment 2: Preprocessing Ablation

- Mục tiêu: So sánh 3 tokenization preprocessing pipeline trên cùng corpus C4 (30K):
    + Pipeline A (Minimal): lowercase + tách khoảng trắng
    + Pipeline B (Normalized): lowercase + chuẩn hóa dấu câu + loại stopword
    + Pipeline C (Extended): chuẩn hóa khoảng trắng + BPE subword (BPE chỉ train trên tập train)
- Protocol: fit vocabulary trên train (80%); đo OOV và self-retrieval MRR@10 trên test (20%)

In [8]:
raw_corpus = corpus.copy()

In [9]:
# Chia tập corpus train/test theo tỷ lệ 8:2
from sklearn.model_selection import train_test_split

train_corpus, test_corpus = train_test_split(
    raw_corpus,
    test_size = 0.2,
    random_state = 42,
    shuffle = True
)

In [10]:
import re
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS, CountVectorizer
from sklearn.preprocessing import normalize

from tokenizers import Tokenizer
from tokenizers.models import BPE
from tokenizers.trainers import BpeTrainer
from tokenizers.pre_tokenizers import Whitespace

# Pipeline A: Minimal - lowercase và tách khoảng trắng
def pipeline_A(document):
    # Viết thường các từ trong document
    document = document.lower()

    # Tách các token
    tokens = document.split()

    return tokens

# Pipeline B: Normalized - lowercase + chuẩn hóa dấu câu + loại stopword
def pipeline_B(document):
    document = document.lower()
    # Tách dấu câu khỏi từ
    document = re.sub(r"[^\w\s]+", " ", document, flags=re.UNICODE)
    document = re.sub(r"\s+", " ", document).strip()
    tokens = document.split()
    tokens = [token for token in tokens if token not in ENGLISH_STOP_WORDS]
    return tokens

# Pipeline C: Extended - Normalization + BPE subword tokenization
# Bước 1: Normalization
def normalize_C(document):
    document = document.lower()                         # Chuyển toàn bộ document về chữ thường
    document = re.sub(r"\s+", " ", document).strip()    # Gộp mọi chuỗi khoảng trắng liên tiếp (Tab, xuống dòng, dấu cách) thành một dấu cách duy nhất, rồi dùng strip() để xóa khoảng trắng thừa ở đầu và cuối câu
    return document

# Áp dụng thuật toán BPE cho subword tokenization
# BPE sẽ gộp các ký tự/subword xuất hiện thường xuyên thành một token mới và lặp lại quá trình này cho đến khi đạt kích thước vocab mong muốn
bpe_tokenizer = Tokenizer(
    BPE(unk_token="[UNK]")  # Token dự phòng cho các kỳ tự thực sự chưa từng thấy trong lúc train
)

# Trước khi áp dụng BPE, document được tách theo khoảng trắng và dấu câu thành các từ "thô". BPE chỉ gộp subword trong phạm vi của mỗi từ "thô".
bpe_tokenizer.pre_tokenizer = Whitespace()

bpe_trainer = BpeTrainer(
    vocab_size=30000,           # Giới hạn số lượng token tối đa trong từ điển cuối cùng
    min_frequency=2,            # Một cặp subword chỉ được gộp thành token mới nếu nó xuất hiện ít nhất 2 lần trong corpus
    special_tokens=["[UNK]"]    # Đảm bảo token đặc biệt này luôn có mặt trong từ điển, không bị BPE học đè
)

# Chuẩn hóa corpus dạng thô để huấn luyện
normalized_train_corpus = [
    normalize_C(document)
    for document in train_corpus
]

# Huấn luyện BPE
bpe_tokenizer.train_from_iterator(
    normalized_train_corpus,
    trainer=bpe_trainer
)

# Hàm xử lý pipeline
def pipeline_C(document):
    document = normalize_C(document)

    encoding = bpe_tokenizer.encode(document)

    return encoding.tokens

In [11]:
# Pipeline A
count_vectorizer_A = CountVectorizer(
    tokenizer = pipeline_A,
    preprocessor = None,
    token_pattern = None,
    lowercase = False
)

count_matrix_A = count_vectorizer_A.fit_transform(train_corpus)

# Pipeline B
count_vectorizer_B = CountVectorizer(
    tokenizer = pipeline_B,
    preprocessor = None,
    token_pattern = None,
    lowercase = False
)

count_matrix_B = count_vectorizer_B.fit_transform(train_corpus)

# Pipeline C
count_vectorizer_C = CountVectorizer(
    tokenizer = pipeline_C,
    preprocessor = None,
    token_pattern = None,
    lowercase = False
)

count_matrix_C = count_vectorizer_C.fit_transform(train_corpus)

In [12]:
from typing import Any


def count_TF_IDF_matrix(count_matrix, return_idf=False):
    # Ma trận TF — tránh chia 0 khi document rỗng
    document_lengths = np.asarray(count_matrix.sum(axis=1)).ravel().astype(float)
    safe_lengths = np.where(document_lengths > 0, document_lengths, 1.0)
    tf_matrix = count_matrix.multiply(1 / safe_lengths[:, None])

    # Vector IDF
    N = count_matrix.shape[0]
    df_vector = np.asarray((count_matrix > 0).sum(axis=0)).ravel()

    idf_vector = np.zeros(df_vector.shape[0], dtype=float)
    mask = df_vector > 0
    idf_vector[mask] = np.log(N / df_vector[mask])

    tf_idf_matrix = tf_matrix.multiply(idf_vector)
    return (tf_idf_matrix, idf_vector) if return_idf else tf_idf_matrix

# Tính trung bình token trong 1 document
def average_tokens_per_document(count_matrix):
    total_tokens_per_document = np.asarray(count_matrix.sum(axis = 1)).ravel()
    total_tokens = sum(total_tokens_per_document)
    total_documents = count_matrix.shape[0]
    return total_tokens / total_documents

# Tính độ thưa trong ma trận TF-IDF
def sparsity(tf_idf_matrix):
    N, V = tf_idf_matrix.shape
    S = 1 - (tf_idf_matrix.nnz / (N * V))
    return S

# Tính tỷ lệ OOV
def count_OOV_rate(test_corpus, vectorizer):
    train_vocab = set(vectorizer.vocabulary_.keys())
    analyzer = vectorizer.build_analyzer()

    total_tokens = 0
    oov_tokens = 0

    for document in test_corpus:
        tokens = analyzer(document)
        total_tokens += len(tokens)

        for token in tokens:
            if token not in train_vocab:
                oov_tokens += 1

    if total_tokens == 0:
        return 0.0

    return oov_tokens / total_tokens

# Đánh giá search performance bằng Mean Reciprocal Rank (MRR)
def mrr(queries, vectorizer, count_matrix, top_k=10):
    """
    Self-retrieval MRR@k, tính theo lô.
    queries: list[dict] - [{"query": str, "relevant_doc_id": int}, ...]
    vectorizer: CountVectorizer đã fit trên train
    count_matrix: count matrix của tập document dùng để search (test_corpus)
    """
    tf_idf_matrix, idf_vector = count_TF_IDF_matrix(count_matrix, return_idf=True)
    doc_matrix = normalize(tf_idf_matrix.tocsr())   # Chuẩn hóa ma trận TF-IDF trên tập train theo chuẩn 'l2', hỗ trợ phần tính toán cosine similarity

    query_texts = [item["query"] for item in queries]
    relevant_ids = np.array([item["relevant_doc_id"] for item in queries])

    # Vectorize tập query về dạng count matrix
    query_count = vectorizer.transform(query_texts)

    # Tính ma trận TF-IDF trên tập query
    query_lengths = np.asarray(query_count.sum(axis=1)).ravel().astype(float)
    safe_query_lengths = np.where(query_lengths > 0, query_lengths, 1.0)

    query_tfidf = query_count.multiply(1 / safe_query_lengths[:, None]).multiply(idf_vector)
    query_tfidf = normalize(query_tfidf.tocsr()).tolil()

    # Xử lý case độ dài câu truy vấn bằng 0 khi tính ma trận TF-IDF
    empty_mask = query_lengths == 0
    if np.any(empty_mask):
        query_tfidf[empty_mask] = 0
    query_tfidf = query_tfidf.tocsr()

    # Tính cosine similarity
    similarities = (query_tfidf @ doc_matrix.T).toarray()   # Ma trận similarity có kích thước (query.length x 30K)
    similarities[empty_mask] = -np.inf

    # Tính MRR
    ranked = np.argsort(-similarities, axis=1)[:, :top_k]   # Lọc ra k document có ranking similarity cao nhất theo từng query
    reciprocal_ranks = np.zeros(len(queries), dtype=float)
    for i, rel in enumerate(relevant_ids):
        if empty_mask[i]:
            continue
        matched = np.where(ranked[i] == rel)[0]
        if len(matched) > 0:
            reciprocal_ranks[i] = 1.0 / (matched[0] + 1)

    return float(reciprocal_ranks.mean())

def generate_queries_from_test(test_corpus, n_queries=300, random_state=42):
    """
    Self-retrieval: lấy câu đầu của document làm query, chính document đó là relevant.
    Chỉ lấy n_queries mẫu để ablation chạy kịp.
    """
    # Chọn ra các document ngẫu nhiên trên tập test
    rng = np.random.default_rng(random_state)
    indices = rng.choice(len(test_corpus), size=min(n_queries, len(test_corpus)), replace=False)

    # Tạo query từ các document
    queries = []
    for doc_id in indices:
        document = test_corpus[doc_id]
        query_text = document.split(".")[0].strip() #Lấy câu đầu tiên trong document
        if not query_text:
            query_text = document[:200] # Nếu rỗng, lấy 200 ký tự đầu trong document
        queries.append({"query": query_text, "relevant_doc_id": int(doc_id)})   # Add vào danh sách truy vấn
    return queries

In [13]:
vocabulary_size = [
    count_matrix_A.shape[1], 
    count_matrix_B.shape[1], 
    count_matrix_C.shape[1]
]
average_tokens_per_doc = [
    average_tokens_per_document(count_matrix_A),
    average_tokens_per_document(count_matrix_B),
    average_tokens_per_document(count_matrix_C)
]

tf_idf_matrix_A = count_TF_IDF_matrix(count_matrix_A)
tf_idf_matrix_B = count_TF_IDF_matrix(count_matrix_B)
tf_idf_matrix_C = count_TF_IDF_matrix(count_matrix_C)

matrix_sparsity = [
    sparsity(tf_idf_matrix_A) * 100,
    sparsity(tf_idf_matrix_B) * 100,
    sparsity(tf_idf_matrix_C) * 100
]

oov_rate = [
    count_OOV_rate(test_corpus, count_vectorizer_A) * 100,
    count_OOV_rate(test_corpus, count_vectorizer_B) * 100,
    count_OOV_rate(test_corpus, count_vectorizer_C) * 100
]

# Sinh bộ query dùng chung cho cả 3 pipeline
queries = generate_queries_from_test(test_corpus, n_queries=300, random_state=42)

# Ma trận đếm của test_corpus theo từng vectorizer
test_count_matrix_A = count_vectorizer_A.transform(test_corpus)
test_count_matrix_B = count_vectorizer_B.transform(test_corpus)
test_count_matrix_C = count_vectorizer_C.transform(test_corpus)

mrr_score = [
    mrr(queries, count_vectorizer_A, test_count_matrix_A, top_k=10),
    mrr(queries, count_vectorizer_B, test_count_matrix_B, top_k=10),
    mrr(queries, count_vectorizer_C, test_count_matrix_C, top_k=10),
]

- Bảng kết quả

In [14]:
import pandas as pd

df = pd.DataFrame(
    [vocabulary_size, average_tokens_per_doc, matrix_sparsity, oov_rate, mrr_score],
    columns = ['Pipeline A', 'Pipeline B', 'Pipeline C'],
    index = ['Vocabulary size', 'Average tokens/document', 'Matrix sparsity (%)', 'OOV rate (%)', 'Search performance (MRR@10)']
)

df.loc['Vocabulary size'] = df.loc['Vocabulary size'].astype(int)
df.loc['Average tokens/document'] = df.loc['Average tokens/document'].round(2)
df.loc['Matrix sparsity (%)'] = df.loc['Matrix sparsity (%)'].round(2)
df.loc['OOV rate (%)'] = df.loc['OOV rate (%)'].round(2)
df.loc['Search performance (MRR@10)'] = df.loc['Search performance (MRR@10)'].round(4)

df

                              Pipeline A  Pipeline B  Pipeline C
Vocabulary size              403095.0000  167777.000   29670.000
Average tokens/document         361.6800     197.230     451.250
Matrix sparsity (%)              99.9500      99.930      99.360
OOV rate (%)                      4.2600       3.600       0.030
Search performance (MRR@10)       0.8712       0.887       0.896

1. Lowercasing giúp giảm bớt những token giống nhau nhưng tách biệt do phân biệt chữ hoa/thường. Ví dụ: Power/power
2. Stopword removal không phải lúc nào cũng cải thiện respresentation.
3. Việc loại punctuation có thể làm mất tính nhận diện của token. Ví dụ: số thập phân
4. Pipeline A tạo ra sparse matrix nhất
5. Pipeline C cho search tốt nhất
6. Search tốt hơn thì chưa chắc vocabulary nhỏ hơn.

# Application: Build a Document Search Engine

In [15]:
from sklearn.preprocessing import normalize as sk_normalize

# Chuẩn hóa (L2-norm) ma trận TF-IDF của corpus
doc_matrix = sk_normalize(tf_idf_matrix.tocsr())

print(f'Doc matrix shape: {doc_matrix.shape}')
print(f'Doc matrix format: {type(doc_matrix)}')

Doc matrix shape: (30000, 473388)
Doc matrix format: <class 'scipy.sparse._csr.csr_matrix'>

In [16]:
import numpy as np


def search(query, vectorizer, idf_vector, doc_matrix, corpus, top_k=5):
    """
    Hệ thống tìm kiếm document dựa trên TF-IDF + Cosine Similarity.

    Input:
        query      : câu truy vấn do người dùng nhập (raw text)
        vectorizer : CountVectorizer đã fit trên corpus
        idf_vector : vector IDF tính trên toàn bộ corpus, shape = (V,)
        doc_matrix : ma trận TF-IDF của corpus, đã được chuẩn hóa L2
                     (mỗi document là một vector đơn vị)
        corpus     : dữ liệu gốc (dùng để lấy đoạn preview hiển thị)
        top_k      : số lượng document trả về

    Output:
        list các tuple (rank, doc_id, similarity_score, document_preview),
        sắp xếp theo similarity giảm dần. Trả về [] nếu query không chứa
        bất kỳ term nào nằm trong vocabulary của corpus.
    """

    # Count vector của query
    query_count = vectorizer.transform([query]).toarray()[0]

    total_terms = query_count.sum()
    if total_terms == 0:
        return []

    # TF của query
    query_tf = query_count / total_terms

    # TF-IDF của query, dùng idf_vector đã tính trên toàn corpus
    query_tfidf = query_tf * idf_vector

    # Chuẩn hóa (L2) query vector để cosine similarity
    query_norm = np.linalg.norm(query_tfidf)
    if query_norm == 0:
        return []
    query_vector = query_tfidf / query_norm

    # Cosine similarity giữa query và toàn bộ corpus.
    scores = doc_matrix @ query_vector

    # Ranking theo similarity giảm dần, lấy top_k
    ranked_indices = np.argsort(scores)[::-1][:top_k]

    results = []
    for rank, doc_id in enumerate(ranked_indices, start=1):
        score = scores[doc_id]
        snippet = corpus[doc_id][:300].replace("\n", " ")
        results.append((rank, int(doc_id), float(score), snippet))

    return results

- Hàm hiển thị kết quả search và in bảng kết quả

In [17]:
def display_search_results(query, results):
    print(f"Query: {query}")
    print("-" * 80)

    if not results:
        print("No matching documents.")
        return

    for rank, doc_id, score, snippet in results:
        print(f"Rank: {rank}")
        print(f"Document ID: {doc_id}")
        print(f"Similarity: {score:.4f}")
        print(f"Preview: {snippet}")
        print("-" * 80)

In [18]:
import pandas as pd


def search_results_table(query, results):
    """
    Hiển thị kết quả search dưới dạng bảng
    """
    if not results:
        print(f'Query: {query}')
        print('No matching documents.')
        return pd.DataFrame(columns=['Rank', 'Document ID', 'Similarity', 'Document preview'])

    table = pd.DataFrame(
        [(rank, doc_id, round(score, 4), snippet) for rank, doc_id, score, snippet in results],
        columns=['Rank', 'Document ID', 'Similarity', 'Document preview']
    )
    return table

- Demo search engine trên các queries

In [27]:
queries = [
    "medical image classification",
    "transformer language model",
    "deep learning healthcare",
    "natural language processing",
    "computer vision",
    "data mining algorithm",
    "heart attack treatment"
]

all_results = {}

for query in queries:
    results = search(
        query,
        vectorizer,
        idf_vector,
        doc_matrix,
        corpus,
        top_k=5
    )

    all_results[query] = results
    display_search_results(query, results)

Query: medical image classification
--------------------------------------------------------------------------------
Rank: 1
Document ID: 27352
Similarity: 0.6188
Preview: The TESTID statement is effective only when you specify the TESTLIST or TESTLISTERR option in the PROC DISCRIM statement. When the DISCRIM procedure displays the classification results for the TESTDATA= data set, the TESTID variable (rather than the observation number) is displayed for each observat
--------------------------------------------------------------------------------
Rank: 2
Document ID: 13607
Similarity: 0.2036
Preview: Stunning Watch More Like Paint Storage Containers Paint Storage Containers - The image above with the title Stunning Watch More Like Paint Storage Containers Paint Storage Containers, is part of Paint Storage Containers picture gallery. Size for this image is 630 × 472, a part of Storage Containers
--------------------------------------------------------------------------------
Rank: 3
Document ID: 10026
Similarity: 0.1855
Preview: Color classification of power input and output connector prevent misoperation of connecting sockets. P5.2 Indoor audiovisual production LED screen is the best option for event on stages, TV stations and concerts. it can be installed horizontally and vertically or be installed separately , the viewin
--------------------------------------------------------------------------------
Rank: 4
Document ID: 18949
Similarity: 0.1639
Preview: Newest Baby Car Seat Replacement Cover for Infant Car Seat Replacement Cover for Graco by Sassycovers. Infant Car Seat Replacement Cover for Graco by sassycovers. Image from: www.etsy.com. A picture about baby car seat replacement cover for the inspiration for car seating inspiration. This is a phot
--------------------------------------------------------------------------------
Rank: 5
Document ID: 10368
Similarity: 0.1599
Preview: Published 04/20/2019 10:40:34 pm at 04/20/2019 10:40:34 pm in Dc Comics Room Decor. dc comics room decor superhero room decor impressive on batman room decor batman room ideas amp superhero room ideas pottery superhero room decor dc comics superhero logos wall decals superman batman room decor super
--------------------------------------------------------------------------------
Query: transformer language model
--------------------------------------------------------------------------------
Rank: 1
Document ID: 6326
Similarity: 0.3100
Preview: Label: butterfly twin comforter set. butterfly twin comforter set girls. 30 piece comforter set. butterfly comforter set twin size. cheetah print comforter set queen. Label: chaps comforter sets queen size. chaps comforter sets queen. 3 piece comforter set king. blue chaps comforter sets. blue queen
--------------------------------------------------------------------------------
Rank: 2
Document ID: 27936
Similarity: 0.2748
Preview: hi, I am having problems with transformer / circuit board om my Hobby 720 uml model 2003. In view of the problems, can I bypass the transformer/circuit board ??
--------------------------------------------------------------------------------
Rank: 3
Document ID: 11723
Similarity: 0.1665
Preview: Welcome to our Piro vocabulary page! Piro is an Arawakan language, related to other languages like Arawak and Ashaninka. We have included twenty basic Piro words here, to compare with related American Indian languages. If you need to know a Piro word that is not currently on our page, you can take p
--------------------------------------------------------------------------------
Rank: 4
Document ID: 26951
Similarity: 0.1482
Preview: Tinashe, cover star of the Autumn Winter 18 issue, has found that no matter how far she goes, or where, home is always with her. She shares with us how she strikes a nuanced balance between who she was, who she is and who she wants to become. Santino Le Saint is the vibrant, young model and artist s
--------------------------------------------------------------------------------
Rank: 5
Document ID: 15853
Similarity: 0.1280
Preview: Why does my battery drain fast when I'm not using the device? Whenever I wake my Transformer up after it has been used for awhile, the amount of charge left in the battery is much lower than I expect. The Transformer is supposed to be in sleep mode, but the battery life has decreased too much for th
--------------------------------------------------------------------------------
Query: deep learning healthcare
--------------------------------------------------------------------------------
Rank: 1
Document ID: 26858
Similarity: 0.2374
Preview: Join our web portal for access to lists of formulas, pricing and prescriber information for products and services available at ACP. Access available for registered healthcare professionals only, as required by law. Enter your email and press Submit to request your password.
--------------------------------------------------------------------------------
Rank: 2
Document ID: 19308
Similarity: 0.1504
Preview: This Summer is ending with me not having spent nearly enough time in my kayak. I have been prioritizing work's needs all year, but I have found a solution. IBM laid me off. Now, my schedule should be wide open for paddling trips, right? Actually, not so much as job hunting is pretty time consuming b
--------------------------------------------------------------------------------
Rank: 3
Document ID: 3969
Similarity: 0.1458
Preview: This is a rare opportunity to purchase a deep-water sound front lot on Bridgers Ave in Topsail Beach. Bridgers is considered THE street to be on in Topsail Beach and this particular lot has never been built upon. Nicely contoured and inviting. Lot is near the end of Bridgers so it is a quiet with ve
--------------------------------------------------------------------------------
Rank: 4
Document ID: 24534
Similarity: 0.1402
Preview: Inspired by a gorgeous photo I saw, this is A View From Above. The ocean brings us many emotions and this artwork is inspired by the feeling of depth and intrigue. Deep greeny blues and sand colours make this a stand out piece. I want you to be over the moon with your purchase! I offer a 30 day 100%
--------------------------------------------------------------------------------
Rank: 5
Document ID: 26542
Similarity: 0.1378
Preview: A weight added or included in terminal tackle for fishing and intended to force the line deep in the water or completely to the bottom. These are typically removable but can be tied permanently to the line, and can be made of lead, tungsten, tin, and other heavy metals. They can be as small as a few
--------------------------------------------------------------------------------
Query: natural language processing
--------------------------------------------------------------------------------
Rank: 1
Document ID: 11723
Similarity: 0.2367
Preview: Welcome to our Piro vocabulary page! Piro is an Arawakan language, related to other languages like Arawak and Ashaninka. We have included twenty basic Piro words here, to compare with related American Indian languages. If you need to know a Piro word that is not currently on our page, you can take p
--------------------------------------------------------------------------------
Rank: 2
Document ID: 16721
Similarity: 0.1857
Preview: EVA foam sheet can be widely use for kids handcraft, a piece of normal EVA foam sheet can be a house, a castle or flower magically. It's non-ammonia, odorless and eco-friendly EVA foam especially for kids, we have over 39 colors for your selection. Customized logo, packing, label and design are avai
--------------------------------------------------------------------------------
Rank: 3
Document ID: 6445
Similarity: 0.1745
Preview: Back end processing in addition to front end UI experience is required. Experience in working with complex queries against databases/tables with large number of records. · Bachelor’s degree in Computer Science with additional coursework in management, information processing or a related field. · May
--------------------------------------------------------------------------------
Rank: 4
Document ID: 9389
Similarity: 0.1464
Preview: This week I was privileged to teach in a local Christian school each morning. I taught sign language and gave my testimony each day. Well, I taught as much sign language as I could in a 45 minute class each day. Plus I used my time to give my testimony and encourage the young people to serve the Lor
--------------------------------------------------------------------------------
Rank: 5
Document ID: 6450
Similarity: 0.1406
Preview: Food Product Specifications sheets here. Please note that these are our standard processing specifications. Specifications maybe negotiated for large quantity orders. Please contact us for further information.
--------------------------------------------------------------------------------
Query: computer vision
--------------------------------------------------------------------------------
Rank: 1
Document ID: 1244
Similarity: 0.3284
Preview: The PC I am using right now is more than six years. I checked my blog and found the post of flash the bios in Feb 2013. I did a search in my Gmail. Wow, I found the receipt which I made the order on NCIX. NCIX has closed for years already. There are three items. All are running on my desktop now. La
--------------------------------------------------------------------------------
Rank: 2
Document ID: 26714
Similarity: 0.2504
Preview: This half day or full day workshop targets strategies for effectively casting your business vision and mission. Implement an effective strategy to accomplish both your vision and mission. Who will benefit from this seminar? Everyone in your organization regardless of the position they hold.
--------------------------------------------------------------------------------
Rank: 3
Document ID: 25950
Similarity: 0.2390
Preview: Since 1987, Anawim Housing has been building homes, hope and community. From its start as a vision of Sister Stella Neill, Anawim Housing has become a local leader in affordable housing. Anawim Housing now owns or manages nearly 740 units.
--------------------------------------------------------------------------------
Rank: 4
Document ID: 21081
Similarity: 0.2323
Preview: Daily Prompt: Faded – Lindeman Chiropractic…don't just survive, THRIVE! Friendships form a solid foundation…Give thanks for relationships, whether they be strong currently or their bonds are more of a remembrance…Friendship should be acknowledged for their absolute amazing importance. Looking at old
--------------------------------------------------------------------------------
Rank: 5
Document ID: 10961
Similarity: 0.2123
Preview: Property For Sale Laurel Ms is free HD wallpaper. This wallpaper was upload at April 22, 2019 upload by admin in .You can download it in your computer by clicking resolution image in Download by size:. Don't forget to rate and comment if you interest with this wallpaper.
--------------------------------------------------------------------------------
Query: data mining algorithm
--------------------------------------------------------------------------------
Rank: 1
Document ID: 4154
Similarity: 0.4402
Preview: Paid search campaigns can be highly effective - and highly time-consuming, and highly complex. We have the expertise and the experience to monitor your campaign and make the ongoing strategic adjustments it needs to remain competitive and lucrative. Every PPC campaign starts with a carefully develop
--------------------------------------------------------------------------------
Rank: 2
Document ID: 3298
Similarity: 0.3992
Preview: Zheng-Chu Guo, Lei Shi, Qiang Wu; 18(118):1−25, 2017. Distributed learning is an effective way to analyze big data. In distributed regression, a typical approach is to divide the big data into multiple blocks, apply a base regression algorithm on each of them, and then simply average the output func
--------------------------------------------------------------------------------
Rank: 3
Document ID: 10677
Similarity: 0.3435
Preview: And in the present Reputation Economy, it’s getting more powerful than ever. Because today, thanks to rapid advances in digital technology, anyone access huge troves of information about you your buying habits, your finances, your professional and personal networks, and even your physical whereabout
--------------------------------------------------------------------------------
Rank: 4
Document ID: 28305
Similarity: 0.2996
Preview: If you type the words ‘I met with’ into a Google search, in Ireland at least, an obliging or very prescriptive algorithm will add the words ‘Napper Tandy’ immediately. I haven’t tried this in the UK, the USA, Uzbekistan or the Falklands so I’m not quite sure if it works there as well. Maybe if you’r
--------------------------------------------------------------------------------
Rank: 5
Document ID: 27213
Similarity: 0.2782
Preview: The main difference between Hadoop and Spark is that the Hadoop is an Apache open source framework that allows distributed processing of large data sets across clusters of computers using simple programming models while Spark is a cluster computing framework designed for fast Hadoop computation. Big
--------------------------------------------------------------------------------
Query: heart attack treatment
--------------------------------------------------------------------------------
Rank: 1
Document ID: 9048
Similarity: 0.3308
Preview: The incidents that took place in the vicinity of Salford Precinct on the 9 August 2011 occurred prior to and took a quite distinct form from the more widespread rioting and looting two miles away in Manchester city-centre. The riot events in Salford occurred following the Greater Manchester Police's
--------------------------------------------------------------------------------
Rank: 2
Document ID: 18006
Similarity: 0.2861
Preview: Exercise high blood pressure and it goes up. But only temporarily. What does it do over the long run? See this Drs Practical Guide and you'll want to start a program today! When you exercise, your muscles demand a lot more circulation of blood, otherwise you won't last long. This increased circulati
--------------------------------------------------------------------------------
Rank: 3
Document ID: 27200
Similarity: 0.2763
Preview: Our Volleyball Insights technology has some pretty awesome implications for our volleyball coaches. Our data visualizations will provide interactive heat maps and other insightful charts that will help you evaluate the tendencies and hitting efficiencies for your team and your opponents. If you're a
--------------------------------------------------------------------------------
Rank: 4
Document ID: 22261
Similarity: 0.2613
Preview: The Vietnam War placed unexpected demands upon American military forces and equipment.The principal US naval fighter, the McDonnell F-4 Phantom, had originally been designed to defend the Fleet from air attack at long range. However, its tremendous power and bomb-carrying capacity made it an obvious
--------------------------------------------------------------------------------
Rank: 5
Document ID: 4778
Similarity: 0.2594
Preview: With the release of FFXIV patch 3.4 - Soul Surrender, many players complain about its content. I want to give some suggestions about this new content for FFXIV. To people who complain about the same-y content, I think that the main idea is that the "1 raid, 1 primal, 2 dungeons per patch" is the bas
--------------------------------------------------------------------------------

In [28]:
combined_table = pd.concat(
    [search_results_table(q, r).assign(Query=q) for q, r in all_results.items()],
    ignore_index=True
)[['Query', 'Rank', 'Document ID', 'Similarity', 'Document preview']]

combined_table

,Query,Rank,Document ID,Similarity,Document preview
0,medical image classification,1,27352,0.6188,The TESTID statement is effective only when yo...
1,medical image classification,2,13607,0.2036,Stunning Watch More Like Paint Storage Contain...
2,medical image classification,3,10026,0.1855,Color classification of power input and output...
3,medical image classification,4,18949,0.1639,Newest Baby Car Seat Replacement Cover for Inf...
4,medical image classification,5,10368,0.1599,Published 04/20/2019 10:40:34 pm at 04/20/2019...
5,transformer language model,1,6326,0.3100,Label: butterfly twin comforter set. butterfly...
6,transformer language model,2,27936,0.2748,"hi, I am having problems with transformer / ci..."
7,transformer language model,3,11723,0.1665,Welcome to our Piro vocabulary page! Piro is a...
8,transformer language model,4,26951,0.1482,"Tinashe, cover star of the Autumn Winter 18 is..."
9,transformer language model,5,15853,0.1280,Why does my battery drain fast when I'm not us...
10,deep learning healthcare,1,26858,0.2374,Join our web portal for access to lists of for...
11,deep learning healthcare,2,19308,0.1504,This Summer is ending with me not having spent...
12,deep learning healthcare,3,3969,0.1458,This is a rare opportunity to purchase a deep-...
13,deep learning healthcare,4,24534,0.1402,"Inspired by a gorgeous photo I saw, this is A ..."
14,deep learning healthcare,5,26542,0.1378,A weight added or included in terminal tackle ...
15,natural language processing,1,11723,0.2367,Welcome to our Piro vocabulary page! Piro is a...
16,natural language processing,2,16721,0.1857,EVA foam sheet can be widely use for kids hand...
17,natural language processing,3,6445,0.1745,Back end processing in addition to front end U...
18,natural language processing,4,9389,0.1464,This week I was privileged to teach in a local...
19,natural language processing,5,6450,0.1406,Food Product Specifications sheets here. Pleas...
20,computer vision,1,1244,0.3284,The PC I am using right now is more than six y...
21,computer vision,2,26714,0.2504,This half day or full day workshop targets str...
22,computer vision,3,25950,0.2390,"Since 1987, Anawim Housing has been building h..."
23,computer vision,4,21081,0.2323,Daily Prompt: Faded – Lindeman Chiropractic…do...
24,computer vision,5,10961,0.2123,Property For Sale Laurel Ms is free HD wallpap...
25,data mining algorithm,1,4154,0.4402,Paid search campaigns can be highly effective ...
26,data mining algorithm,2,3298,0.3992,"Zheng-Chu Guo, Lei Shi, Qiang Wu; 18(118):1−25..."
27,data mining algorithm,3,10677,0.3435,"And in the present Reputation Economy, it’s ge..."
28,data mining algorithm,4,28305,0.2996,If you type the words ‘I met with’ into a Goog...
29,data mining algorithm,5,27213,0.2782,The main difference between Hadoop and Spark i...
30,heart attack treatment,1,9048,0.3308,The incidents that took place in the vicinity ...
31,heart attack treatment,2,18006,0.2861,Exercise high blood pressure and it goes up. B...
32,heart attack treatment,3,27200,0.2763,Our Volleyball Insights technology has some pr...
33,heart attack treatment,4,22261,0.2613,The Vietnam War placed unexpected demands upon...
34,heart attack treatment,5,4778,0.2594,With the release of FFXIV patch 3.4 - Soul Sur...

# Evaluation

In [29]:
# In ra candidate documents (top-K theo TF-IDF search ở Part G)
for query in queries:
    print(f"Query: {query}")
    print("-" * 80)
    for rank, doc_id, score, snippet in all_results[query]:
        print(f"  [{doc_id}] score={score:.4f} | {snippet}")
    print()

manual_relevance = {
    "medical image classification": [],
    "transformer language model": [],
    "deep learning healthcare": [],
    "natural language processing": [],
    "computer vision": [],
    "data mining algorithm": [3298, 27213],
    "heart attack treatment": [18006, 25228]
}

evaluation_set = [
    {"query": q, "relevant_doc_ids": manual_relevance[q]}
    for q in queries
]

for i, item in enumerate(evaluation_set, start=1):
    print(f"Query {i}: {item['query']}")
    print(f"Relevant: {item['relevant_doc_ids']}")
    print('-' * 80)

Query: medical image classification
--------------------------------------------------------------------------------
  [27352] score=0.6188 | The TESTID statement is effective only when you specify the TESTLIST or TESTLISTERR option in the PROC DISCRIM statement. When the DISCRIM procedure displays the classification results for the TESTDATA= data set, the TESTID variable (rather than the observation number) is displayed for each observat
  [13607] score=0.2036 | Stunning Watch More Like Paint Storage Containers Paint Storage Containers - The image above with the title Stunning Watch More Like Paint Storage Containers Paint Storage Containers, is part of Paint Storage Containers picture gallery. Size for this image is 630 × 472, a part of Storage Containers
  [10026] score=0.1855 | Color classification of power input and output connector prevent misoperation of connecting sockets. P5.2 Indoor audiovisual production LED screen is the best option for event on stages, TV stations and concerts. it can be installed horizontally and vertically or be installed separately , the viewin
  [18949] score=0.1639 | Newest Baby Car Seat Replacement Cover for Infant Car Seat Replacement Cover for Graco by Sassycovers. Infant Car Seat Replacement Cover for Graco by sassycovers. Image from: www.etsy.com. A picture about baby car seat replacement cover for the inspiration for car seating inspiration. This is a phot
  [10368] score=0.1599 | Published 04/20/2019 10:40:34 pm at 04/20/2019 10:40:34 pm in Dc Comics Room Decor. dc comics room decor superhero room decor impressive on batman room decor batman room ideas amp superhero room ideas pottery superhero room decor dc comics superhero logos wall decals superman batman room decor super

Query: transformer language model
--------------------------------------------------------------------------------
  [6326] score=0.3100 | Label: butterfly twin comforter set. butterfly twin comforter set girls. 30 piece comforter set. butterfly comforter set twin size. cheetah print comforter set queen. Label: chaps comforter sets queen size. chaps comforter sets queen. 3 piece comforter set king. blue chaps comforter sets. blue queen
  [27936] score=0.2748 | hi, I am having problems with transformer / circuit board om my Hobby 720 uml model 2003. In view of the problems, can I bypass the transformer/circuit board ??
  [11723] score=0.1665 | Welcome to our Piro vocabulary page! Piro is an Arawakan language, related to other languages like Arawak and Ashaninka. We have included twenty basic Piro words here, to compare with related American Indian languages. If you need to know a Piro word that is not currently on our page, you can take p
  [26951] score=0.1482 | Tinashe, cover star of the Autumn Winter 18 issue, has found that no matter how far she goes, or where, home is always with her. She shares with us how she strikes a nuanced balance between who she was, who she is and who she wants to become. Santino Le Saint is the vibrant, young model and artist s
  [15853] score=0.1280 | Why does my battery drain fast when I'm not using the device? Whenever I wake my Transformer up after it has been used for awhile, the amount of charge left in the battery is much lower than I expect. The Transformer is supposed to be in sleep mode, but the battery life has decreased too much for th

Query: deep learning healthcare
--------------------------------------------------------------------------------
  [26858] score=0.2374 | Join our web portal for access to lists of formulas, pricing and prescriber information for products and services available at ACP. Access available for registered healthcare professionals only, as required by law. Enter your email and press Submit to request your password.
  [19308] score=0.1504 | This Summer is ending with me not having spent nearly enough time in my kayak. I have been prioritizing work's needs all year, but I have found a solution. IBM laid me off. Now, my schedule should be wide open for paddling trips, right? Actually, not so much as job hunting is pretty time consuming b
  [3969] score=0.1458 | This is a rare opportunity to purchase a deep-water sound front lot on Bridgers Ave in Topsail Beach. Bridgers is considered THE street to be on in Topsail Beach and this particular lot has never been built upon. Nicely contoured and inviting. Lot is near the end of Bridgers so it is a quiet with ve
  [24534] score=0.1402 | Inspired by a gorgeous photo I saw, this is A View From Above. The ocean brings us many emotions and this artwork is inspired by the feeling of depth and intrigue. Deep greeny blues and sand colours make this a stand out piece. I want you to be over the moon with your purchase! I offer a 30 day 100%
  [26542] score=0.1378 | A weight added or included in terminal tackle for fishing and intended to force the line deep in the water or completely to the bottom. These are typically removable but can be tied permanently to the line, and can be made of lead, tungsten, tin, and other heavy metals. They can be as small as a few

Query: natural language processing
--------------------------------------------------------------------------------
  [11723] score=0.2367 | Welcome to our Piro vocabulary page! Piro is an Arawakan language, related to other languages like Arawak and Ashaninka. We have included twenty basic Piro words here, to compare with related American Indian languages. If you need to know a Piro word that is not currently on our page, you can take p
  [16721] score=0.1857 | EVA foam sheet can be widely use for kids handcraft, a piece of normal EVA foam sheet can be a house, a castle or flower magically. It's non-ammonia, odorless and eco-friendly EVA foam especially for kids, we have over 39 colors for your selection. Customized logo, packing, label and design are avai
  [6445] score=0.1745 | Back end processing in addition to front end UI experience is required. Experience in working with complex queries against databases/tables with large number of records. · Bachelor’s degree in Computer Science with additional coursework in management, information processing or a related field. · May
  [9389] score=0.1464 | This week I was privileged to teach in a local Christian school each morning. I taught sign language and gave my testimony each day. Well, I taught as much sign language as I could in a 45 minute class each day. Plus I used my time to give my testimony and encourage the young people to serve the Lor
  [6450] score=0.1406 | Food Product Specifications sheets here. Please note that these are our standard processing specifications. Specifications maybe negotiated for large quantity orders. Please contact us for further information.

Query: computer vision
--------------------------------------------------------------------------------
  [1244] score=0.3284 | The PC I am using right now is more than six years. I checked my blog and found the post of flash the bios in Feb 2013. I did a search in my Gmail. Wow, I found the receipt which I made the order on NCIX. NCIX has closed for years already. There are three items. All are running on my desktop now. La
  [26714] score=0.2504 | This half day or full day workshop targets strategies for effectively casting your business vision and mission. Implement an effective strategy to accomplish both your vision and mission. Who will benefit from this seminar? Everyone in your organization regardless of the position they hold.
  [25950] score=0.2390 | Since 1987, Anawim Housing has been building homes, hope and community. From its start as a vision of Sister Stella Neill, Anawim Housing has become a local leader in affordable housing. Anawim Housing now owns or manages nearly 740 units.
  [21081] score=0.2323 | Daily Prompt: Faded – Lindeman Chiropractic…don't just survive, THRIVE! Friendships form a solid foundation…Give thanks for relationships, whether they be strong currently or their bonds are more of a remembrance…Friendship should be acknowledged for their absolute amazing importance. Looking at old
  [10961] score=0.2123 | Property For Sale Laurel Ms is free HD wallpaper. This wallpaper was upload at April 22, 2019 upload by admin in .You can download it in your computer by clicking resolution image in Download by size:. Don't forget to rate and comment if you interest with this wallpaper.

Query: data mining algorithm
--------------------------------------------------------------------------------
  [4154] score=0.4402 | Paid search campaigns can be highly effective - and highly time-consuming, and highly complex. We have the expertise and the experience to monitor your campaign and make the ongoing strategic adjustments it needs to remain competitive and lucrative. Every PPC campaign starts with a carefully develop
  [3298] score=0.3992 | Zheng-Chu Guo, Lei Shi, Qiang Wu; 18(118):1−25, 2017. Distributed learning is an effective way to analyze big data. In distributed regression, a typical approach is to divide the big data into multiple blocks, apply a base regression algorithm on each of them, and then simply average the output func
  [10677] score=0.3435 | And in the present Reputation Economy, it’s getting more powerful than ever. Because today, thanks to rapid advances in digital technology, anyone access huge troves of information about you your buying habits, your finances, your professional and personal networks, and even your physical whereabout
  [28305] score=0.2996 | If you type the words ‘I met with’ into a Google search, in Ireland at least, an obliging or very prescriptive algorithm will add the words ‘Napper Tandy’ immediately. I haven’t tried this in the UK, the USA, Uzbekistan or the Falklands so I’m not quite sure if it works there as well. Maybe if you’r
  [27213] score=0.2782 | The main difference between Hadoop and Spark is that the Hadoop is an Apache open source framework that allows distributed processing of large data sets across clusters of computers using simple programming models while Spark is a cluster computing framework designed for fast Hadoop computation. Big

Query: heart attack treatment
--------------------------------------------------------------------------------
  [9048] score=0.3308 | The incidents that took place in the vicinity of Salford Precinct on the 9 August 2011 occurred prior to and took a quite distinct form from the more widespread rioting and looting two miles away in Manchester city-centre. The riot events in Salford occurred following the Greater Manchester Police's
  [18006] score=0.2861 | Exercise high blood pressure and it goes up. But only temporarily. What does it do over the long run? See this Drs Practical Guide and you'll want to start a program today! When you exercise, your muscles demand a lot more circulation of blood, otherwise you won't last long. This increased circulati
  [27200] score=0.2763 | Our Volleyball Insights technology has some pretty awesome implications for our volleyball coaches. Our data visualizations will provide interactive heat maps and other insightful charts that will help you evaluate the tendencies and hitting efficiencies for your team and your opponents. If you're a
  [22261] score=0.2613 | The Vietnam War placed unexpected demands upon American military forces and equipment.The principal US naval fighter, the McDonnell F-4 Phantom, had originally been designed to defend the Fleet from air attack at long range. However, its tremendous power and bomb-carrying capacity made it an obvious
  [4778] score=0.2594 | With the release of FFXIV patch 3.4 - Soul Surrender, many players complain about its content. I want to give some suggestions about this new content for FFXIV. To people who complain about the same-y content, I think that the main idea is that the "1 raid, 1 primal, 2 dungeons per patch" is the bas

Query 1: medical image classification
Relevant: []
--------------------------------------------------------------------------------
Query 2: transformer language model
Relevant: []
--------------------------------------------------------------------------------
Query 3: deep learning healthcare
Relevant: []
--------------------------------------------------------------------------------
Query 4: natural language processing
Relevant: []
--------------------------------------------------------------------------------
Query 5: computer vision
Relevant: []
--------------------------------------------------------------------------------
Query 6: data mining algorithm
Relevant: [3298, 27213]
--------------------------------------------------------------------------------
Query 7: heart attack treatment
Relevant: [18006, 25228]
--------------------------------------------------------------------------------

- Tính Precision@K, Recall@K

In [30]:
def precision_at_k(retrieved_doc_ids, relevant_doc_ids, k=5):
    retrieved_k = retrieved_doc_ids[:k]
    n_relevant_retrieved = len(set(retrieved_k) & set(relevant_doc_ids))
    return n_relevant_retrieved / k


def recall_at_k(retrieved_doc_ids, relevant_doc_ids, k=5):
    if len(relevant_doc_ids) == 0:
        return 0.0
    retrieved_k = retrieved_doc_ids[:k]
    n_relevant_retrieved = len(set(retrieved_k) & set(relevant_doc_ids))
    return n_relevant_retrieved / len(relevant_doc_ids)

- Tính MRR

In [31]:
def reciprocal_rank(retrieved_doc_ids, relevant_doc_ids):
    for rank, doc_id in enumerate(retrieved_doc_ids, start=1):
        if doc_id in relevant_doc_ids:
            return 1.0 / rank
    return 0.0


def mean_reciprocal_rank(all_reciprocal_ranks):
    if len(all_reciprocal_ranks) == 0:
        return 0.0
    return sum(all_reciprocal_ranks) / len(all_reciprocal_ranks)

In [32]:
K = 5
SEARCH_TOP_K = 10  # lấy rộng hơn K để MRR có thể "bắt" được relevant doc nằm ngoài top-5

eval_records = []
all_reciprocal_ranks = []

for item in evaluation_set:
    query = item['query']
    relevant_doc_ids = item['relevant_doc_ids']

    results = search(query, vectorizer, idf_vector, doc_matrix, corpus, top_k=SEARCH_TOP_K)
    retrieved_doc_ids = [doc_id for (_, doc_id, _, _) in results]

    p_at_k = precision_at_k(retrieved_doc_ids, relevant_doc_ids, k=K)
    r_at_k = recall_at_k(retrieved_doc_ids, relevant_doc_ids, k=K)
    rr = reciprocal_rank(retrieved_doc_ids, relevant_doc_ids)
    all_reciprocal_ranks.append(rr)

    eval_records.append({
        'query': query,
        'relevant_doc_ids': relevant_doc_ids,
        'retrieved_doc_ids': retrieved_doc_ids,
        f'P@{K}': p_at_k,
        f'R@{K}': r_at_k,
        'RR': rr
    })

mrr_score_eval = mean_reciprocal_rank(all_reciprocal_ranks)

eval_df = pd.DataFrame(eval_records)
eval_df

,query,relevant_doc_ids,retrieved_doc_ids,P@5,R@5,RR
0,medical image classification,[],"[27352, 13607, 10026, 18949, 10368, 11534, 639...",0.0,0.0,0.0
1,transformer language model,[],"[6326, 27936, 11723, 26951, 15853, 6443, 9389,...",0.0,0.0,0.0
2,deep learning healthcare,[],"[26858, 19308, 3969, 24534, 26542, 12746, 1599...",0.0,0.0,0.0
3,natural language processing,[],"[11723, 16721, 6445, 9389, 6450, 13690, 8632, ...",0.0,0.0,0.0
4,computer vision,[],"[1244, 26714, 25950, 21081, 10961, 20115, 5497...",0.0,0.0,0.0
5,data mining algorithm,"[3298, 27213]","[4154, 3298, 10677, 28305, 27213, 11247, 12987...",0.4,1.0,0.5
6,heart attack treatment,"[18006, 25228]","[9048, 18006, 27200, 22261, 4778, 25228, 13602...",0.2,0.5,0.5

In [33]:
summary_df = pd.DataFrame({
    f'Precision@{K}': [eval_df[f'P@{K}'].mean()],
    f'Recall@{K}': [eval_df[f'R@{K}'].mean()],
    'MRR': [mrr_score_eval]
})

print('Kết quả đánh giá trung bình trên evaluation set:')
summary_df

Kết quả đánh giá trung bình trên evaluation set:

   Precision@5  Recall@5       MRR
0     0.085714  0.214286  0.142857

In [34]:
# Lưu kết quả retrieval/evaluation ra results.csv (deliverable của lab, mục 17)
results_export = eval_df.copy()
results_export.to_csv('results.csv', index=False)
print('Đã lưu results.csv')

Đã lưu results.csv